Repository codeit-sprint-fullstack/2-Sprint-Mission-BE, pull requests merged in 2024-09, with the labels that each got.

#2 [방신철] sprint 6
  .gitignore
  README.md
  app.js
  data/mock.js
  data/seed.js
  env.js
  models/Product.js
  package-lock.json
  package.json
Labels: 매운맛🔥, 제출 완료

#8 [이예린] Sprint6
  sprint6/.gitignore
  sprint6/app.js
  sprint6/data/seed.js
  sprint6/models/Product.js
  sprint6/package-lock.json
  sprint6/package.json
  sprint6/requsets.http
Labels: 순한맛🐑, 제출 완료

#9 [신지원] Sprint6
  .gitignore
  .vscode/settings.json
  app.js
  data/mock.js
  data/seed.js
  models/Product.js
  package-lock.json
  package.json
Labels: 매운맛🔥, 제출 완료

#10 [김태연] Sprint6
  .gitignore
  app.js
  config.js
  data/mock.js
  data/seed.js
  models/Product.js
  package-lock.json
  package.json
  requests.http
Labels: 매운맛🔥, 제출 완료

#6 [김태영] Sprint6
  .gitignore
  app.js
  data/mock.js
  data/mock_seq.js
  data/seed.js
  models/Product.js
  package-lock.json
  package.json
Labels: 매운맛🔥, 제출 완료

#11 [이강수] sprint6
  .gitignore
  product-api/.gitignore
  product-api/README sprint6.md
  product-api/app.js
  product-api/data/mock.js
  product-api/data/seed.js
  product-api/models/Product.js
  product-api/package-lock.json
  product-api/package.json
  product-api/requests.http
Labels: 매운맛🔥, 제출 완료

#12 [강명곤] sprint4 재제출
  .gitignore
  ArticleService.js
  ProductService.js
  main.js
  package-lock.json
  package.json
Labels: 제출 완료

#1 [서유림] Sprint 6
  .gitignore
  app.js
  data/mock.js
  data/seed.js
  models/Product.js
  package-lock.json
  package.json
  requests.http
Labels: 순한맛🐑, 제출 완료

#4 [이도엽] Sprint6
  .gitignore
  app.js
  data/mock.js
  data/seed.js
  models/Product.js
  package-lock.json
  package.json
  request.http
Labels: 매운맛🔥, 제출 완료

#5 [소재희] Sprint6
  .gitignore
  app.js
  data/mock.js
  data/seed.js
  models/Product.js
  package-lock.json
  package.json
  requests.http
Labels: 매운맛🔥, 제출 완료

#3 [양가현] Sprint6
  .gitignore
  README.md
  app.js
  error.js
  models/Products.js
  package-lock.json
  package.json
  request.http
Labels: 매운맛🔥, 제출 완료

#23 [김태연] Sprint7
  app.js
  data/mock.js
  data/seed.js
  helper.js
  https/requests.http
  models/Product.js
  package-lock.json
  package.json
  prisma/migrations/20240923013611_init/migration.sql
  prisma/migrations/20240923022855_start/migration.sql
  prisma/migrations/20240923051609_imprement_add_model_user_article_comment/migration.sql
  prisma/migrations/20240923084220_implement_add_content_field_in_the_comment_model/migration.sql
  prisma/migrations/20240923092212_split_commnet_model_into_product_comment_and_article_comment_models/migration.sql
  prisma/migrations/20240924012109_implment_add_created_at_updated_at_in_product_comment_and_article_comment/migration.sql
  prisma/migrations/20240924012737_fix_change_fieldi_name_article_comment_to_article_comments/migration.sql
  prisma/migrations/20240924043145_add_cascade_in_product_article_product_comment_article_comment/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  requests.http
  structs.js
Labels: 매운맛🔥, 제출 완료

#20 [이예린]Sprint7
  sprint7/.gitignore
  sprint7/app.js
  sprint7/controllers/articleController.js
  sprint7/controllers/commentController.js
  sprint7/controllers/productController.js
  sprint7/http/articles-comment.http
  sprint7/http/articles.http
  sprint7/http/product-comment.http
  sprint7/http/products.http
  sprint7/middlewares/asyncHandler.js
  sprint7/package-lock.json
  sprint7/package.json
  sprint7/prisma/migrations/20240918114512_init/migration.sql
  sprint7/prisma/migrations/20240920051300_schema_init/migration.sql
  sprint7/prisma/migrations/20240923051958_seprate_article_product_comments/migration.sql
  sprint7/prisma/migrations/20240923072005_add_ondelete_option/migration.sql
  sprint7/prisma/migrations/migration_lock.toml
  sprint7/prisma/mock.js
  sprint7/prisma/schema.prisma
  sprint7/prisma/seed.js
  sprint7/routes/articleRoutes.js
  sprint7/routes/commentRoutes.js
  sprint7/routes/productRoutes.js
  sprint7/struct.js
Labels: 순한맛🐑, 제출 완료

#7 [김영은] Sprint 6
  .github/pull-request-template.md
  .github/workflows/auto-label-assign.yml
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  Models/Product.js
  README.md
  app.js
  data/seed.js
  package-lock.json
  package.json
Labels: 매운맛🔥, 제출 완료

#15 [김태영] sprint7
  .gitignore
  data/mock.js
  data/seed.js
  package-lock.json
  package.json
  prisma/migrations/20240916235126_init/migration.sql
  prisma/migrations/20240917072854_rename_indexes/migration.sql
  prisma/migrations/20240917074713_add_article_comment_models/migration.sql
  prisma/migrations/20240917074807_disable_favorite_user_field/migration.sql
  prisma/migrations/20240917075721_rename_article_field_name/migration.sql
  prisma/migrations/20240918101634_edit_ondelete/migration.sql
  prisma/migrations/20240918114609_rename_comment_fk_name/migration.sql
  prisma/migrations/20240918115306_add_comment_product_relation/migration.sql
  prisma/migrations/20240918125043_edit_default_id_of_article_ownerid/migration.sql
  prisma/migrations/20240918125139_edit_ondelete_article_ownership/migration.sql
  prisma/migrations/20240918125255_rollback_ondelete/migration.sql
  prisma/migrations/20240918125721_edit_default_value_comment_owner_id/migration.sql
  prisma/migrations/20240924011238_add_product_images_tags_relations/migration.sql
  prisma/migrations/20240924022228_delete_indexs/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/app.js
  src/constants.js
  src/error.js
  src/mongodb/configs/mongodb.config.js
  src/mongodb/containers/product.container.js
  src/mongodb/controllers/product.controller.js
  src/mongodb/db/mongodb.connection.js
  src/mongodb/models/product.model.js
  src/mongodb/schemas/product.schema.js
  src/mongodb/services/product.service.js
  src/mongodb/utils/async-handler.js
  src/mongodb/utils/error.js
  src/postgresql/configs/postgres.config.js
  src/postgresql/connection/postgres.connection.js
  src/postgresql/containers/article.container.js
  src/postgresql/containers/comment.container.js
  src/postgresql/containers/product.container.js
  src/postgresql/containers/user.container.js
  src/postgresql/controllers/article.controller.js
  src/postgresql/controllers/comment.controller.js
  src/postgresql/controllers/product.controller.js
  src/postgresql/controllers/user.controller.js
  src/postgresql/db/article.db.js
  src/postgresql/db/comment.db.js
  src/postgresql/db/product.db.js
  src/postgresql/db/user.db.js
  src/postgresql/services/article.service.js
  src/postgresql/services/comment.service.js
  src/postgresql/services/product.service.js
  src/postgresql/services/user.service.js
  src/struct.js
Labels: 매운맛🔥, 제출 완료

#25 Express 이강수 sprint7
  DATABASE setup of Panda Market by kipid.html
  README general.md
  README sprint7.md
  product-api/app.js
  sprint7/.gitignore
  sprint7/app.js
  sprint7/helper/encrypt.js
  sprint7/http/articles.http
  sprint7/http/comments.http
  sprint7/http/products.http
  sprint7/http/users.http
  sprint7/package-lock.json
  sprint7/package.json
  sprint7/prisma/migrations/20240924134441_init/migration.sql
  sprint7/prisma/migrations/20240925003310_ing/migration.sql
  sprint7/prisma/migrations/20240925072923_add_indexes_on_comments_updated_at_desc/migration.sql
  sprint7/prisma/migrations/20240925073357_index_with_commenter_id/migration.sql
  sprint7/prisma/migrations/migration_lock.toml
  sprint7/prisma/mock.js
  sprint7/prisma/schema.prisma
  sprint7/prisma/seed.js
  sprint7/structs.js
Labels: 매운맛🔥, 제출 완료

#27 [신지원] Sprint7
  app.js
  data/seed.js
  models/Product.js
  package-lock.json
  package.json
  prisma/migrations/20240927071919_init/migration.sql
  prisma/migrations/20240927072624_add_product_table/migration.sql
  prisma/migrations/20240927074506_add_description_schema/migration.sql
  prisma/migrations/20240927125725_alter_favorite_cnt_default0/migration.sql
  prisma/migrations/20240927142249_add_article_comment_relation/migration.sql
  prisma/migrations/20240927142926_add_article_images_fav_cnt_column/migration.sql
  prisma/migrations/20240927144629_add_product_comment_relation/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  struct.js
Labels: 매운맛🔥, 제출 완료

#28 [강명곤] sprint 7
  README.md
  app.js
  controllers/articleCommentController.js
  controllers/articleController.js
  controllers/productCommentController.js
  controllers/productController.js
  data/seed.js
  middleware/asyncHandler.js
  package-lock.json
  package.json
  prisma/migrations/20240925001051_init/migration.sql
  prisma/migrations/20240925011017_argument_price_change/migration.sql
  prisma/migrations/20240925012452_product_tags_and_product_images_delete/migration.sql
  prisma/migrations/20240925012959_add_product_argument_tags_images/migration.sql
  prisma/migrations/20240929111532_add_product_userid/migration.sql
  prisma/migrations/20240929112909_user_product_relations_and_alter_product_userid/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  routes/articleCommentsRoute.js
  routes/articlesRoute.js
  routes/productCommentsRoute.js
  routes/productsRoute.js
  structs.js
Labels: 매운맛🔥, 제출 완료
