Repository codeit-sprint-fullstack/2-Sprint-Mission-BE, pull requests merged in 2024-10, with the labels that each got.

#17 [소재희] sprint7
  .gitignore
  app.js
  controllers/articleCommentController.js
  controllers/articleController.js
  controllers/productCommentController.js
  controllers/productController.js
  http/articleComments.http
  http/articles.http
  http/productComments.http
  http/products.http
  middleware/ayncHandler.js
  package-lock.json
  package.json
  prisma/migrations/20240920135840_add_user_product_article_comment/migration.sql
  prisma/migrations/20240920141715_add_userpreference/migration.sql
  prisma/migrations/20240920142144_add_field_saveduser_savedproduct/migration.sql
  prisma/migrations/20240922092834_add_tags_to_product/migration.sql
  prisma/migrations/20240922130823_add_article_comment_product_comment/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  requests.http
  routes/articleCommentsRoute.js
  routes/articlesRoute.js
  routes/productCommentsRoute.js
  routes/productsRoute.js
  structs.js
  utils/prismaClient.js
Labels: 매운맛🔥, 제출 완료

#18 [서유림] Sprint 7
  .gitignore
  README.md
  app.js
  controllers/articleCommentController.js
  controllers/articleController.js
  controllers/productCommentController.js
  controllers/productController.js
  data/mock.js
  data/seed.js
  http/articleComment.http
  http/articles.http
  http/productComment.http
  http/products.http
  models/Product.js
  models/articleCommentModel.js
  models/articleModel.js
  models/productCommentModel.js
  models/productModel.js
  package-lock.json
  package.json
  prisma/migrations/20240923023257_init/migration.sql
  prisma/migrations/20240923073126_add_article_schema/migration.sql
  prisma/migrations/20240924073137_add_comment_schema/migration.sql
  prisma/migrations/20240924074617_remove_user_and_author_id/migration.sql
  prisma/migrations/20240924083034_add_ondelete/migration.sql
  prisma/migrations/20240924090534_add_product_id/migration.sql
  prisma/migrations/20240924090735_update_schema/migration.sql
  prisma/migrations/20240924091223_add_product_comment/migration.sql
  prisma/migrations/20240924092257_update/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  requests.http
  routes/articleCommentRoutes.js
  routes/articleRoutes.js
  routes/productCommentRoutes.js
  routes/productRoutes.js
  structs.js
  utils/globalErrorHandler.js
  utils/handleError.js
  utils/requestLogger.js
  utils/responseLogger.js
Labels: 순한맛🐑, 제출 완료

#19 [이도엽] Sprint 7
  .gitignore
  README.md
  app.js
  data/seed.js
  http/articleComment.http
  http/articles.http
  http/productComment.http
  http/products.http
  models/Product.js
  package-lock.json
  package.json
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  request.http
  structs.js
Labels: 매운맛🔥, 제출 완료

#16 [양가현] Sprint7
  README.md
  app.js
  package-lock.json
  package.json
  prisma/migrations/20240922051352_init/migration.sql
  prisma/migrations/20240922113702_fix_product_discription_name/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: 매운맛🔥, 제출 완료

#22 [김민선] sprint6
  .gitignore
  .vscode/settings.json
  app.js
  data/mock.js
  data/seed.js
  models/Product.js
  package-lock.json
  package.json
  requests.http
Labels: 매운맛🔥, 제출일 이후 제출한PR
