Repository codeit-sprint-fullstack/2-Sprint-Mission-BE, pull requests merged in 2024-11, with the labels that each got.

#31 [김민선] sprint10
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  prisma/migrations/20241113054240_init/migration.sql
  prisma/migrations/20241113071421_comment_fields_optional/migration.sql
  prisma/migrations/20241114135817_optional_user_image_encrypted_password_for_test/migration.sql
  prisma/migrations/20241114162328_delete_optional_encrypted_password/migration.sql
  prisma/migrations/20241115073614_add_refresh_token/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/mock.ts
  prisma/schema.prisma
  prisma/seed.ts
  src/app.ts
  src/appConfig.ts
  src/containers/productContainer.ts
  src/containers/userContainer.ts
  src/controllers/productController.ts
  src/controllers/userController.ts
  src/middlewares/auth.ts
  src/middlewares/errorHandler.ts
  src/middlewares/structs.ts
  src/middlewares/validateProduct.ts
  src/repositories/productRepository.ts
  src/repositories/userRepository.ts
  src/routes/productRoutes.ts
  src/routes/userRoutes.ts
  src/services/productService.ts
  src/services/userService.ts
  src/types/productType.ts
  src/types/requestType.ts
  src/types/userType.ts
  tsconfig.json
Labels: 매운맛🔥, 진행 중 🏃

#35 [소재희] Sprint10
  app.js
  controllers/articleController.js
  controllers/productCommentController.js
  controllers/productController.js
  http/productComments.http
  http/products.http
  http/user.http
  package-lock.json
  package.json
  prisma/migrations/20241113093343_update_user_schema/migration.sql
  prisma/migrations/20241113093625_update_user_schema_2/migration.sql
  prisma/migrations/20241114044320_update_user/migration.sql
  prisma/migrations/20241114063340_update_user/migration.sql
  prisma/migrations/20241114070407_update_id_type/migration.sql
  prisma/migrations/20241114084801_change_nickname_to_lowcase/migration.sql
  prisma/migrations/20241116074128_change_category_optional/migration.sql
  prisma/migrations/20241116075355_set_stock_default_zero/migration.sql
  prisma/migrations/20241117043353_update_schema_structure/migration.sql
  prisma/mock_backup.js
  prisma/schema.prisma
  prisma/seed.js
  routes/articlesRoute.js
  routes/productCommentsRoute.js
  routes/productsRoute.js
  src/app.js
  src/config/passport.js
  src/config/prismaClient.js
  src/controllers/articleCommentController.js
  src/controllers/articleController.js
  src/controllers/productCommentController.js
  src/controllers/productController.js
  src/controllers/userController.js
  src/middlewares/asyncHandler.js
  src/middlewares/auth.js
  src/middlewares/errorHandler.js
  src/middlewares/passport/googleStrategy.js
  src/middlewares/passport/jwtStrategy.js
  src/middlewares/passport/localStrategy.js
  src/repositories/articleRepository.js
  src/repositories/productCommentRepository.js
  src/repositories/productRepository.js
  src/repositories/userRepository.js
  src/services/articleCommentService.js
  src/services/articleService.js
  src/services/productCommentService.js
  src/services/productFavoriteService.js
  src/services/productService.js
  src/services/userService.js
  src/structs.js
Labels: 매운맛🔥, 진행 중 🏃

#40 [신지원] Sprint10
  app.js
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.js
  src/config/prisma.js
  src/controllers/articleController.js
  src/controllers/authController.js
  src/controllers/commentController.js
  src/controllers/imageController.js
  src/controllers/productController.js
  src/controllers/userController.js
  src/middlewares/asyncHandler.js
  src/middlewares/auth.js
  src/middlewares/errorHandler.js
  src/middlewares/passport/jwtStrategy.js
  src/middlewares/upload.js
  src/repositories/articleRepository.js
  src/repositories/authRepository.js
  src/repositories/commentRepository.js
  src/repositories/productRepository.js
  src/repositories/userRepository.js
  src/routes/articleRouter.js
  src/routes/authRouter.js
  src/routes/commentRouter.js
  src/routes/productRouter.js
  src/routes/userRouter.js
  src/services/articleService.js
  src/services/authService.js
  src/services/commentService.js
  src/services/productService.js
  src/services/userServices.js
  src/utils/filterSensitiveUserData.js
  struct.js
Labels: 매운맛🔥, 진행 중 🏃

#38 [방신철] sprint10
  app.js
  package-lock.json
  package.json
  prisma/migrations/20240923094407_init/migration.sql
  prisma/migrations/20240923095848_add_article_model/migration.sql
  prisma/migrations/20240924013120_fixed_text_article_content/migration.sql
  prisma/migrations/20240924021142_fixed_model_article_cancel_images/migration.sql
  prisma/migrations/20240924042405_fixed_article_model/migration.sql
  prisma/migrations/20240924061357_add_comment_model/migration.sql
  prisma/migrations/20240924062038_add_product_comment_relation/migration.sql
  prisma/migrations/20240924062418_add_article_comment_relation/migration.sql
  prisma/migrations/20240924151936_comment_model_fixed/migration.sql
  prisma/migrations/20241114044040_new_migrate_schema/migration.sql
  prisma/migrations/20241114090849_add_favorite_model/migration.sql
  prisma/migrations/20241114095738_add_favorite_model_relation_other_model/migration.sql
  prisma/mock.js
  prisma/schema.prisma
  prisma/seed.js
  src/app.js
  src/config/prisma.js
  src/controllers/articleController.js
  src/controllers/commentController.js
  src/controllers/productController.js
  src/controllers/userController.js
  src/middlewares/auth.js
  src/middlewares/errorHandler.js
  src/middlewares/upload.js
  src/repositories/userRepository.js
  src/services/userService.js
  src/testImgUrl.html
  structs.js
  uploads/1731572143958.png
Labels: 매운맛🔥, 제출 완료

#36 [이강수] sprint10
  .gitignore
  sprint10/README sprint10.md
  sprint10/http/test.http
  sprint10/package-lock.json
  sprint10/package.json
  sprint10/prisma/migrations/20241111015341_init/migration.sql
  sprint10/prisma/migrations/20241111063708_add_favorite_count/migration.sql
  sprint10/prisma/migrations/20241112012702_add_favorites/migration.sql
  sprint10/prisma/migrations/20241113021324_add_images_on_article/migration.sql
  sprint10/prisma/migrations/migration_lock.toml
  sprint10/prisma/mock.js
  sprint10/prisma/schema.prisma
  sprint10/prisma/seed.js
  sprint10/src/app.js
  sprint10/src/config/passport.js
  sprint10/src/config/prisma.js
  sprint10/src/controllers/articleController.js
  sprint10/src/controllers/productController.js
  sprint10/src/controllers/reviewController.js
  sprint10/src/controllers/userController.js
  sprint10/src/httpStatus.js
  sprint10/src/middlewares/auth.js
  sprint10/src/middlewares/errorHandler.js
  sprint10/src/middlewares/passport/googleStrategy.js
  sprint10/src/middlewares/passport/jwtStrategy.js
  sprint10/src/middlewares/passport/localStrategy.js
  sprint10/src/repositories/articleCommentRepository.js
  sprint10/src/repositories/articleRepository.js
  sprint10/src/repositories/productCommentRepository.js
  sprint10/src/repositories/productRepository.js
  sprint10/src/repositories/reviewRepository.js
  sprint10/src/repositories/userRepository.js
  sprint10/src/services/articleCommentService.js
  sprint10/src/services/articleService.js
  sprint10/src/services/productCommentService.js
  sprint10/src/services/productService.js
  sprint10/src/services/reviewService.js
  sprint10/src/services/userService.js
  sprint10/src/structs.js
  sprint10/uploads/1731471235283-ì¸ì¸ ìë­ì¹ ìì .png
  sprint10/uploads/1731487658562-ì¸ì¸ ë²ë¬ë©.jpg
  sprint7/prisma/migrations/20241022053832_add_favorite_count_to_article/migration.sql
  sprint7/prisma/migrations/20241023235359_add_unique_on_user_nickname/migration.sql
Labels: 순한맛🐑, 제출 완료
